import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Мета-теги, стили и прочее, если требуется */}
      </head>
      <body className={inter.className}>
        <header>
          <div className="container">
            <div className="header">
            <div className="logo"><img src="/logo.svg" alt="Logo" /></div>
             <div className="cart"><img src="/cart.svg" alt="Cart" /> <div className="digitcart">0</div></div>
            </div>
          </div>

        </header>

        {children} {/* Содержимое конкретной страницы будет здесь */}

        {/* Добавьте здесь footer, если он нужен */}
      </body>
    </html>
  );
}
